import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import MainNavigation from "@/components/main-header";

const poppins = Poppins({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} flex flex-col min-h-screen`}
        suppressHydrationWarning
      >
        <MainNavigation />
        {children}
      </body>
    </html>
  );
}
